#!/usr/bin/env bash
set -eux -o pipefail
: "${BUILD_SSH_PASSWORD:?BUILD_SSH_PASSWORD is required}"

SCRIPT=$(cat <<'MAINEND'
gawk -i inplace -f- /etc/ssh/sshd_config <<'EOF'
BEGIN { update = "PasswordAuthentication yes" }
/^[#\s]*PasswordAuthentication\s/ { $0 = update; found = 1 }
{ print }
ENDFILE { if (!found) print update }
EOF

gawk -i inplace -f- /etc/ssh/sshd_config <<'EOF'
BEGIN { update = "PermitRootLogin yes" }
/^[#\s]*PermitRootLogin\s/ { $0 = update; found = 1 }
{ print }
ENDFILE { if (!found) print update }
EOF

systemctl restart sshd
MAINEND
)

cat<<EOF
ETH0_METHOD='dhcp'
NETWORK='YES'
SET_HOSTNAME='SlurmAccounting'
PASSWORD='${BUILD_SSH_PASSWORD}'
ETH0_MAC='00:11:22:33:44:55'
START_SCRIPT_BASE64="$(echo "$SCRIPT" | base64 -w0)"
EOF
