# frozen_string_literal: true

ONEAPP_SLURM_MUNGE_KEY_BASE64 = env :ONEAPP_SLURM_MUNGE_KEY_BASE64, ''
ONEAPP_SLURM_CLUSTER_NAME = env :ONEAPP_SLURM_CLUSTER_NAME, 'one'
ONEAPP_SLURM_SERVICE_NETWORK = env :ONEAPP_SLURM_SERVICE_NETWORK, ''

ONEAPP_SLURM_DBD_PORT = env :ONEAPP_SLURM_DBD_PORT, '6819'
ONEAPP_SLURM_DB_HOST = env :ONEAPP_SLURM_DB_HOST, ''
ONEAPP_SLURM_DB_BACKUP_HOST = env :ONEAPP_SLURM_DB_BACKUP_HOST, ''
ONEAPP_SLURM_DB_PORT = env :ONEAPP_SLURM_DB_PORT, '3306'
ONEAPP_SLURM_DB_NAME = env :ONEAPP_SLURM_DB_NAME, 'slurm_acct_db'
ONEAPP_SLURM_DB_USER = env :ONEAPP_SLURM_DB_USER, 'slurm'
ONEAPP_SLURM_DB_PASSWORD = env :ONEAPP_SLURM_DB_PASSWORD, ''
ONEAPP_SLURM_ARCHIVE_DIR = env :ONEAPP_SLURM_ARCHIVE_DIR, '/var/lib/slurmdbd/archive'
ONEAPP_SLURM_PURGE_JOB_AFTER = env :ONEAPP_SLURM_PURGE_JOB_AFTER, '12months'
ONEAPP_SLURM_PURGE_TXN_AFTER = env :ONEAPP_SLURM_PURGE_TXN_AFTER, '12months'
ONEAPP_SLURM_PURGE_USAGE_AFTER = env :ONEAPP_SLURM_PURGE_USAGE_AFTER, '24months'

ONEAPP_LDAP_ENABLE = env :ONEAPP_LDAP_ENABLE, 'NO'
ONEAPP_LDAP_DOMAIN = env :ONEAPP_LDAP_DOMAIN, 'slurm.local'
ONEAPP_LDAP_ADMIN_USER = env :ONEAPP_LDAP_ADMIN_USER, ''
ONEAPP_LDAP_ADMIN_PASSWORD = env :ONEAPP_LDAP_ADMIN_PASSWORD, ''
ONEAPP_LDAP_URL = env :ONEAPP_LDAP_URL, ''
ONEAPP_LDAP_BIND_USER = env :ONEAPP_LDAP_BIND_USER, ''
ONEAPP_LDAP_BIND_PASSWORD = env :ONEAPP_LDAP_BIND_PASSWORD, ''

LDAP_CONFIGURED_MARKER = '/etc/ldap/one_slurm_ldap_configured'
LDAP_EXTERNAL_ADMIN_DN = 'gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth'
