# frozen_string_literal: true
INSTALL_INFINIBAND        = env :INSTALL_INFINIBAND, 'true'

ONEAPP_LDAP_ENABLE        = env :ONEAPP_LDAP_ENABLE, 'NO'
ONEAPP_LDAP_DOMAIN        = env :ONEAPP_LDAP_DOMAIN, 'slurm.local'
ONEAPP_LDAP_ADMIN_USER    = env :ONEAPP_LDAP_ADMIN_USER, 'admin'
ONEAPP_LDAP_ADMIN_PASSWORD = env :ONEAPP_LDAP_ADMIN_PASSWORD, ''
ONEAPP_LDAP_URL           = env :ONEAPP_LDAP_URL, ''
ONEAPP_LDAP_BIND_USER     = env :ONEAPP_LDAP_BIND_USER, ''
ONEAPP_LDAP_BIND_PASSWORD = env :ONEAPP_LDAP_BIND_PASSWORD, ''
ONEAPP_SLURM_INFINIBAND_ENABLE = env :ONEAPP_SLURM_INFINIBAND_ENABLE,
                                      'NO'
ONEAPP_SLURM_STATE_SAVE_LOCATION = env :ONEAPP_SLURM_STATE_SAVE_LOCATION,
                                       '/var/spool/slurmctld'
ONEAPP_SLURM_CLUSTER_NAME = env :ONEAPP_SLURM_CLUSTER_NAME, 'one'
ONEAPP_SLURM_MAX_NODE_COUNT = env :ONEAPP_SLURM_MAX_NODE_COUNT, '100'
ONEAPP_SLURM_MUNGE_KEY_BASE64 = env :ONEAPP_SLURM_MUNGE_KEY_BASE64, ''
ONEAPP_SLURM_ACCOUNTING_ENABLE = env :ONEAPP_SLURM_ACCOUNTING_ENABLE, 'NO'
ONEAPP_SLURM_ACCOUNTING_HOST = env :ONEAPP_SLURM_ACCOUNTING_HOST, ''
ONEAPP_SLURM_ACCOUNTING_BACKUP_HOST = env :ONEAPP_SLURM_ACCOUNTING_BACKUP_HOST, ''
ONEAPP_SLURM_ACCOUNTING_PORT = env :ONEAPP_SLURM_ACCOUNTING_PORT, '6819'
ONEAPP_SLURM_CONSTRAIN_CORES = env :ONEAPP_SLURM_CONSTRAIN_CORES, 'YES'
ONEAPP_SLURM_CONSTRAIN_RAM = env :ONEAPP_SLURM_CONSTRAIN_RAM, 'YES'
ONEAPP_SLURM_CONSTRAIN_SWAP = env :ONEAPP_SLURM_CONSTRAIN_SWAP, 'YES'
ONEAPP_SLURM_CONSTRAIN_DEVICES = env :ONEAPP_SLURM_CONSTRAIN_DEVICES, 'YES'

LDAP_CONFIGURED_MARKER = '/etc/ldap/one_slurm_ldap_configured'
LDAP_EXTERNAL_ADMIN_DN = 'gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth'
