# frozen_string_literal: true

INSTALL_DRIVERS               = env :INSTALL_DRIVERS, 'true'
INSTALL_INFINIBAND            = env :INSTALL_INFINIBAND, 'true'
NVIDIA_DRIVER_BRANCH          = env :NVIDIA_DRIVER_BRANCH, '595'
ONEAPP_SLURM_INFINIBAND_ENABLE = env :ONEAPP_SLURM_INFINIBAND_ENABLE,
                                      'NO'
ONEAPP_SLURM_IPOIB_SUBNET      = env :ONEAPP_SLURM_IPOIB_SUBNET, ''
ONEAPP_SLURM_SERVICE_NETWORK      = env :ONEAPP_SLURM_SERVICE_NETWORK, ''
ONEAPP_SLURM_MUNGE_KEY_BASE64    = env :ONEAPP_SLURM_MUNGE_KEY_BASE64, ''
ONEAPP_LDAP_BIND_USER            = env :ONEAPP_LDAP_BIND_USER, ''
ONEAPP_LDAP_BIND_PASSWORD        = env :ONEAPP_LDAP_BIND_PASSWORD, ''
ONEAPP_SLURM_SYSTEM_RESERVED_MEMORY_MB = env :ONEAPP_SLURM_SYSTEM_RESERVED_MEMORY_MB, '0'
